services:
  minio: 
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
    container_name: minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: qimpe
      MINIO_ROOT_PASSWORD: pass12345
    volumes:
      - minio-storage:/data


  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/static
      - ./media:/media
  

volumes:
 minio-storage:
 postgres-storage: