# Generated by Django 5.2.4 on 2025-07-18 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('slug', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(upload_to='artists_images/')),
                ('bio', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('in_pending', 'На рассмотрении'), ('Rejected', 'Отклонен')], default='in_pending', max_length=15)),
                ('balance', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('is_explicit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(upload_to='music_covers/')),
                ('release_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('in_pending', 'На рассмотрении'), ('Rejected', 'Отклонен')], default='in_pending', max_length=15)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('genre', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='music.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('is_explicit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='favorite', max_length=128, unique=True, verbose_name='Мне нравится')),
                ('cover', models.ImageField(upload_to='playlists_covers/')),
                ('genre', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='music.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('is_explicit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(upload_to='music_covers/')),
                ('audio_file', models.FileField(upload_to='tracks/')),
                ('release_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('in_pending', 'На рассмотрении'), ('Rejected', 'Отклонен')], default='in_pending', max_length=15)),
                ('genre', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='music.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
