# Generated by Django 5.2.4 on 2025-07-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_album_slug_alter_playlist_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackinalbum',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('in_pending', 'На рассмотрении'), ('rejected', 'Отклонен')], default='in_pending', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('in_pending', 'На рассмотрении'), ('rejected', 'Отклонен')], default='in_pending', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('in_pending', 'На рассмотрении'), ('rejected', 'Отклонен')], default='in_pending', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='trackinalbum',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
