# Generated by Django 5.2.4 on 2025-07-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_album_is_explicit_alter_playlist_is_explicit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_explicit',
            field=models.BooleanField(default=False, verbose_name='Возрастное ограничение 18+'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_explicit',
            field=models.BooleanField(default=False, verbose_name='Возрастное ограничение 18+'),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_explicit',
            field=models.BooleanField(default=False, verbose_name='Возрастное ограничение 18+'),
        ),
    ]
