# Generated by Django 5.2.4 on 2025-07-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_album_is_explicit_alter_album_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
