# Generated by Django 5.2.4 on 2025-07-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_artisttrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='bpm',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='decade_emerged',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='origin_country',
            field=models.CharField(default='01.01.01', max_length=100),
            preserve_default=False,
        ),
    ]
