# Generated by Django 5.2.4 on 2025-07-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_genre_bpm_genre_decade_emerged_genre_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='bpm',
        ),
        migrations.AddField(
            model_name='genre',
            name='max_bpm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='min_bpm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
