# Generated by Django 5.2.4 on 2025-07-27 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('created', 'Создан'), ('in_pending', 'На рассмотрении'), ('rejected', 'Отклонен'), ('deleted', 'Удален')], default='in_pending', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('created', 'Создан'), ('in_pending', 'На рассмотрении'), ('rejected', 'Отклонен'), ('deleted', 'Удален')], default='created', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('created', 'Создан'), ('in_pending', 'На рассмотрении'), ('rejected', 'Отклонен'), ('deleted', 'Удален')], default='in_pending', max_length=15, verbose_name='Статус'),
        ),
    ]
