# Generated by Django 5.2.4 on 2025-08-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_delete_userartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='hsl_playlist',
            field=models.FileField(null=True, upload_to='tracks/'),
        ),
    ]
