# Generated by Django 5.2.4 on 2025-08-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_track_hsl_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='hsl_playlist',
            new_name='hls_playlist',
        ),
        migrations.AddField(
            model_name='track',
            name='is_hls_processed',
            field=models.BooleanField(default=False),
        ),
    ]
