# Generated by Django 5.2.4 on 2025-08-08 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_alter_trackmetadata_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumartist',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='music.album'),
        ),
        migrations.AlterField(
            model_name='albumartist',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='albumgenres',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_genre', to='music.album'),
        ),
        migrations.AlterField(
            model_name='albumgenres',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_album', to='music.genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artisttrack',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_track', to='music.artist'),
        ),
        migrations.AlterField(
            model_name='artisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_artist', to='music.track'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='playlistgenres',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_playlist', to='music.genre'),
        ),
        migrations.AlterField(
            model_name='playlistgenres',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_genre', to='music.playlist'),
        ),
        migrations.AlterField(
            model_name='trackgenres',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre', to='music.genre'),
        ),
        migrations.AlterField(
            model_name='trackgenres',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_genres', to='music.track'),
        ),
        migrations.AlterField(
            model_name='trackinalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_tracks', to='music.album'),
        ),
        migrations.AlterField(
            model_name='trackinalbum',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='music.track'),
        ),
        migrations.AlterField(
            model_name='trackinplaylist',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='music.playlist'),
        ),
        migrations.AlterField(
            model_name='trackinplaylist',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='music.track'),
        ),
        migrations.AlterField(
            model_name='trackmetadata',
            name='track',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='music.track'),
        ),
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
        migrations.AlterModelTable(
            name='albumartist',
            table='album_artist',
        ),
        migrations.AlterModelTable(
            name='albumgenres',
            table='album_genres',
        ),
        migrations.AlterModelTable(
            name='artist',
            table='artist',
        ),
        migrations.AlterModelTable(
            name='artisttrack',
            table='artist_track',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
        migrations.AlterModelTable(
            name='playlist',
            table='playlist',
        ),
        migrations.AlterModelTable(
            name='playlistgenres',
            table='playlist_genres',
        ),
        migrations.AlterModelTable(
            name='track',
            table='track',
        ),
        migrations.AlterModelTable(
            name='trackgenres',
            table='track_genres',
        ),
        migrations.AlterModelTable(
            name='trackinalbum',
            table='track_in_album',
        ),
        migrations.AlterModelTable(
            name='trackinplaylist',
            table='track_in_playlist',
        ),
        migrations.AlterModelTable(
            name='trackmetadata',
            table='track_metadata',
        ),
    ]
