# Generated by Django 5.2.4 on 2025-08-08 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_alter_albumartist_album_alter_albumartist_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinalbum',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_album', to='music.track'),
        ),
    ]
