# Generated by Django 5.2.4 on 2025-07-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_album_title_alter_track_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_explicit',
            field=models.BooleanField(blank=True, default=False, verbose_name='Возрастное ограничение 18+'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_explicit',
            field=models.BooleanField(blank=True, default=False, verbose_name='Возрастное ограничение 18+'),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_explicit',
            field=models.BooleanField(blank=True, default=False, verbose_name='Возрастное ограничение 18+'),
        ),
    ]
