# Generated by Django 5.2.4 on 2025-07-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_artist_created_at_alter_album_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='track',
            name='idx_track_artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
    ]
