# Generated by Django 5.2.4 on 2025-07-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_artist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserArtist',
        ),
    ]
