# Generated by Django 5.2.4 on 2025-08-03 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_rename_hsl_playlist_track_hls_playlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmetadata',
            name='track',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_metadata', to='music.track'),
        ),
    ]
